### ISSUE TITLE
high-frequency data

### ISSUE THREAD

**Issue by waynelapierre** [gregorkastner/stochvol#14]
Is it appropriate to use this stochvol package with high-frequency financial data, such as tick-by-tick exchange rate return?

**Comment by hdarjus** [comment]
Not directly, no. However, if you can account for intraday microstructure through some additional hierarchy, then you can use one of [`svsample_fast_cpp`](https://github.com/gregorkastner/stochvol/blob/f25c2b2c27c077f0031f83510a7fec7a27a64916/R/exports.R#L125) (without leverage effect) or [`svsample_general_cpp`](https://github.com/gregorkastner/stochvol/blob/f25c2b2c27c077f0031f83510a7fec7a27a64916/R/exports.R#L140) (with leverage effect) for sampling the SV part. A good starting point can be [10.1016/J.CSDA.2008.07.039](https://doi.org/10.1016/J.CSDA.2008.07.039).
