### ISSUE TITLE
Export further cpp functions

### ISSUE THREAD

**Issue by hdarjus** [gregorkastner/stochvol#17]
A user would like to use these functions in their R package:

```
cholesky_tridiagonal
forward_algorithm
backward_algorithm
inverse_transform_sampling
find_mixture_indicator_cdf
```

**Comment by hdarjus** [comment]
158e5418798f7cb7ec084cef132daef67bc326e0

**Comment by donotdespair** [comment]
Many thanks @hdarjus ! I will now proceed to rewrite my package based on these functions directly!
