### ISSUE TITLE
acceptance_rate_beta. proposal sd of phi

### ISSUE THREAD

**Issue by luisgruber** [gregorkastner/stochvol#24]
Hi Darjus,

I am wondering whether the standard deviations are correct in the following lines:
https://github.com/gregorkastner/stochvol/blob/0bf8fca1587a1ca5897baa2934015e7240ce76e0/src/utils_parameters.cc#L232-L233.
I think that the proposal sd of phi is different from the proposal sd of gamma (proposal_intercept_sd), isn't it?

**Comment by hdarjus** [comment]
Hi @luisgruber, your proposal looks valid, thank you. I need to sit down and work myself through the changes. I'll keep you updated.

**Comment by hdarjus** [comment]
Accepted. Thanks!
