### ISSUE TITLE
R CMD check --as-cran / TODO before next submission

### ISSUE THREAD

**Issue by gregorkastner** [gregorkastner/stochvol#4]
R CMD check --as-cran shows

Found the following (possibly) invalid URLs:
  URL: https://CRAN.R-project.org/package=stochvol/vignettes/paper.pdf
    From: inst/CITATION
    Status: 404
    Message: Not Found

This is OK (as the vignette will not be available there until the package has been published on CRAN) but has to be explicitly addressed in the COMMENTS field when submitted to CRAN.

**Comment by hdarjus** [comment]
We did it!
